spring:
  application:
    name: Fast&Furious Cinema
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:cinema}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

server:
  servlet:
    contextPath: /api
omdb:
  apiKey: ${OMDB_API_KEY}
  baseUrl: http://www.omdbapi.com/
  cacheDir: cache/omdb
resilience4j:
  retry:
    instances:
      omdbApi:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  circuitbreaker:
    instances:
      omdbApi:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
